WITH REST_AVG_REVIEW AS (
    SELECT REST_ID,
        AVG(REVIEW_SCORE) AS "SCORE"
    FROM REST_REVIEW
    GROUP BY REST_ID
)
SELECT RI.REST_ID,
    RI.REST_NAME,
    RI.FOOD_TYPE,
    RI.FAVORITES,
    RI.ADDRESS,
    ROUND(RAR.SCORE, 2) AS "SCORE"
FROM REST_INFO RI
JOIN REST_AVG_REVIEW RAR ON RI.REST_ID = RAR.REST_ID
WHERE RI.ADDRESS LIKE '서울%'
ORDER BY 6 DESC, 4 DESC
